# Generated by Django 2.2 on 2020-05-17 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categroys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy', models.CharField(max_length=15, verbose_name='影片分类')),
            ],
            options={
                'verbose_name': '影片分类',
                'verbose_name_plural': '影片分类',
            },
        ),
        migrations.CreateModel(
            name='M_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='影片名')),
                ('director', models.CharField(default='未知', max_length=30, verbose_name='导演')),
                ('scriptwriter', models.CharField(default='未知', max_length=10, verbose_name='编剧')),
                ('actors', models.CharField(blank=True, default='未知', max_length=20, verbose_name='主演')),
                ('country', models.CharField(default='未知', max_length=10, verbose_name='国家')),
                ('language', models.CharField(default='未知', max_length=20, verbose_name='语言')),
                ('time', models.CharField(default='未知', max_length=15, verbose_name='时长')),
                ('contends', models.TextField(default='暂无', max_length=300, verbose_name='简介')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Categroys', verbose_name='影片分类')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
                'ordering': ['-created_time'],
            },
        ),
    ]
